remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
title: Douglas Figueroa
description: Data engineer, AWS Certified Solutions Architect, Python and SQL dev.
